services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 5001:5000
    restart: unless-stopped
    networks:
     - host-global
    container_name: LyricMuse

networks:
  host-global:
    external: true